### ISSUE TITLE
Integrate Inbox with S3 backend

### ISSUE THREAD

**Issue by dtitov** [neicnordic/sda-inbox-sftp#10]
### Description
We would like to use S3 as a storage back-end for the Inbox in order to not require Inbox and Ingest to share the same volume in Docker Swarm setup. 

Possible solutions:
- Use [S3 Multipart Uploads](https://docs.aws.amazon.com/AmazonS3/latest/dev/llJavaUploadFile.html). **Pros**: we don't make upload time longer as the file will be uploaded to S3 at the same time as it's being uploaded to the Inbox itself. **Cons**: it can be tricky to recover interrupted upload (when Inbox microservice fails and restarts). More information [here](https://stackoverflow.com/questions/53764876/resume-s3-multipart-upload-partetag).
- Use "staging area": first upload files to local storage (as it is now) and then upload them to S3. **Pros**: more stable solution, no need to add some persistence complexity to support resumable uploads. **Cons**: we make upload time twice longer because we basically upload file two times (User -> Staging, Staging -> S3). 

I'll try the first option first (using [MapDB](http://www.mapdb.org/) library, suggested by @juhtornr). If it won't work, I'll go for the second option.

### Definition of Done
Files end up in new S3 server after they are uploaded to the Inbox.

### How to test
Run the int-tests in the [LocalEGA-deploy-swarm](https://github.com/NBISweden/LocalEGA-deploy-swarm) repo and make sure that it passes with the new approach.

**Comment by silverdaz** [comment]
Probably worth looking at [NFS over HTTP](http://www.nfsv4bat.org/Documents/ConnectAThon/2000/shoaib.pdf).

**Comment by dtitov** [comment]
Done: https://jenkins.norgene.no/blue/organizations/jenkins/LocalEGA-deploy-swarm/detail/test%2Fs3-inbox/1/pipeline
