### ISSUE TITLE
Select log-level based on env-var

### ISSUE THREAD

**Issue by dtitov** [neicnordic/sda-inbox-sftp#30]
### Description
The level of logging should be configurable via an environment variable.

### Proposed solution
Inject env-var value to Spring properties.

### Definition of Done
Based on the value of env-var logging detalization can be changed.

**Comment by dtitov** [comment]
I've started implementing this issue and realized that it's already implemented via built-in Spring feature. 

Different loggers can be configured using corresponding package names, for example, to turn of logs of Spring, one can set env var `LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=OFF`, or to set Mina's own logs to debug: `LOGGING_LEVEL_SE_NBIS_LEGA_INBOX=DEBUG`, etc.

So, I'm closing this issue for now.

**Comment by blankdots** [comment]
@dtitov Could you place this information in the `Readme.md` so that it would be more visible for others. After that we can close the issue.

**Comment by dtitov** [comment]
OK
